// Every ID was checked via YouTube oEmbed: embeddable, and uploaded by the artist's or label's own channel.
window.SONGS=[
{title:"Chahana Eutai Mero",artist:"Nabin K Bhattarai",youtubeId:"13jNoqQWBTc",featured:true},
{title:"Resham",artist:"Nepathya",youtubeId:"BpeFXed4K6I"},
{title:"Jogale Huncha Bheta",artist:"Nepathya",youtubeId:"7vBL2JF6SdI"},
{title:"Siran Ma Photo Chha",artist:"Nepathya",youtubeId:"3ImKq4nGqdM"},
{title:"Bhedako Oon Jasto",artist:"Nepathya",youtubeId:"Jy0gLuvTfXk"},
{title:"Sa Karnali",artist:"Nepathya",youtubeId:"mbeeEo09A5A"},
{title:"Himal Chuchure",artist:"Nepathya",youtubeId:"a9gyWfaI8MQ"},
{title:"Sirfula Siraima",artist:"Nepathya",youtubeId:"pwTfUhPSmHE"},
{title:"Kasaile Sodhe",artist:"Nepathya",youtubeId:"Glbw1eNIesM"},
{title:"Nepali Ho",artist:"1974 AD",youtubeId:"UMPwJ9AJdog"},
{title:"Jati Maya Laye Pani",artist:"1974 AD",youtubeId:"OFotUtyt5_M"},
{title:"Mildaina Kathaharu",artist:"1974 AD",youtubeId:"JTrIXBdcIIY"},
{title:"Pahilo Junima",artist:"1974 AD",youtubeId:"1tRHOkXkxyA"},
{title:"Chaina",artist:"Albatross",youtubeId:"LBE-k4IcjT8"},
{title:"Timi Bhane",artist:"Albatross",youtubeId:"4oR9hq7QQKU"},
{title:"Nischal",artist:"Albatross",youtubeId:"SC5c-AzmCbs"},
{title:"Manav Nai Danav",artist:"Albatross",youtubeId:"oGn8lJ3he34"},
{title:"Awaz",artist:"Albatross",youtubeId:"OpRcbBVqXf0"},
{title:"Din",artist:"Anuprastha",youtubeId:"uM5cv4NPVls"},
{title:"Nepal Sworga Bhanda Thulo Cha",artist:"Anuprastha",youtubeId:"apor_sWk7lU"},
{title:"Mercedes Benz",artist:"Cobweb",youtubeId:"WwNk-zjdAqc"},
{title:"Maryo Ni Mayro",artist:"Cobweb",youtubeId:"oav9ymS2Nck"},
{title:"Jay Nepal",artist:"Cobweb",youtubeId:"uJ1nc7LaDFE"},
{title:"Shatru... Ma Afai",artist:"Cobweb",youtubeId:"i87vAQrNkdk"},
{title:"Ekanta Chha Thau",artist:"Crews On Destiny (COD)",youtubeId:"eCXbUpP8vAI"},
{title:"Aakhama Timilai",artist:"Nabin K Bhattarai",youtubeId:"Tpq1_Uflleg"},
{title:"Timi Hau Lakhau Ko Dhadkan",artist:"Nabin K Bhattarai",youtubeId:"h9lFxdIUNmI"},
{title:"Sanjh Dhaldhai Chha",artist:"Nabin K Bhattarai",youtubeId:"PIKlSusL-a0"},
{title:"Chiuri Phool",artist:"Mt. 8848",youtubeId:"TL1m1_hHxuU"},
{title:"Jeu Ko Masu",artist:"Mt. 8848",youtubeId:"DnD52jSGP6U"},
{title:"Saathi (60)",artist:"Mt. 8848",youtubeId:"Gz_Jw6PXUQ8"},
{title:"Lachaar",artist:"Mt. 8848",youtubeId:"qtoDfDPZhqQ"},
{title:"Parkhaima",artist:"Raju Lama (Mongolian Heart)",youtubeId:"cCxjAMIB0-k"},
{title:"Sayad Timro Batoma",artist:"Raju Lama (Mongolian Heart)",youtubeId:"RNOkuiXkmmQ"},
{title:"Geet Milan Ka",artist:"Crossroads",youtubeId:"MrKBC_wZ78s"},
{title:"Pheri Tyo Din",artist:"Sugam Pokharel",youtubeId:"iOevI_gKeK4"},
{title:"Jadai Chu Tadha",artist:"Sugam Pokharel",youtubeId:"rrm98rTABo4"},
{title:"Timi Nai Hau",artist:"Sabin Rai",youtubeId:"L6aC_lKIajY"},
{title:"Sannani",artist:"Kutumba",youtubeId:"31O8vtEVT7E"},
{title:"Jaba Sandhya Hunchha",artist:"Yogeshwar Amatya",youtubeId:"r1Bd96CVC78"}
];
